# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: diki.karim@easipos.com
author_name: dikikarim2020
cloud_provider: none
contract_name: deficuan
deployment_language: python
preset_name: production
project_name: DefiCuan

