# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.6
_src_path: gh:algorandfoundation/algokit-python-template
author_email: diki.karim@easipos.com
author_name: dikikarim2020
contract_name: deficuan
deployment_language: python
preset_name: production
project_name: DefiCuan-contracts

